language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-9.1.17.0
  - jruby-9.2.5.0
  - jruby-head
  - ruby-head
  - truffleruby
matrix:
  include:
    - rvm: 1.9.3
      dist: trusty
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-9.0.5.0
    - rvm: truffleruby
before_install:
  - gem install bundler || gem install bundler --version '< 2'
script: bundle exec rake spec_travis
gemfile: .travis.gemfile
before_script:
  - mysql -e 'create database sequel_test;'
  - psql -c 'create database sequel_test;' -U postgres
addons:
  postgresql: "9.6"
services:
  - postgresql
  - mysql
