language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-9.1.17.0
  - jruby-9.2.0.0
  - jruby-head
  - truffleruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-9.0.5.0
before_install:
  - gem install bundler
script: bundle exec rake spec_travis
gemfile: .travis.gemfile
before_script:
  - mysql -e 'create database sequel_test;'
  - psql -c 'create database sequel_test;' -U postgres
addons:
  postgresql: "9.6"
services:
  - postgresql
