language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-9.1.12.0
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: jruby-19mode
before_install:
  - gem install bundler
script: bundle exec rake spec_travis
gemfile: .travis.gemfile
before_script:
  - mysql -e 'create database sequel_test;'
  - psql -c 'create database sequel_test;' -U postgres
addons:
  postgresql: "9.4"
services:
  - postgresql
